### ISSUE TITLE
Configure Renovate

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/sdk-python#9]
In order for renovate to create an issue for version updates/maintenance that we can get added to the core board we need to review and merge the following PR:

https://github.com/vegaprotocol/sdk-python/pull/7

**Comment by wwestgarth** [comment]
All the updates suggested by renovate are updates to either github-worlflows or linters that run by the CI, so harmless in that they will not in any way affect the functionality of the SDK itself, but valuable because its always good to keep out infrastructure up to date.

I've merged it in.
